Repository pagopa/pagopa-notifications-service, pull requests merged in 2023-07, with the labels that each got.

#60 CHK-1540: Fix branch tag deploy
  .devops/deploy-pipelines.yml
Labels: size/small

#61 fix(deploy-pipeline): dependency graph
  .devops/deploy-pipelines.yml
Labels: size/small

#62 feat(CD): deploy on pr merge
  .devops/deploy-pipelines.yml
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
  README.md
Labels: skip-release

#63 fix(helm-values): remove unused secret
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, ignore-for-release, chart-patch

#64 fix: pr number extraction
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, skip-release

#65 [CHK-1720] update-logo-ref
  .env.example
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, patch
