Repository pagopa/pagopa-notifications-service, pull requests merged in 2025-04, with the labels that each got.

#100 fix: helm values for canary deployment
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/deploy-pipelines.yml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, ignore-for-release, chart-patch

#105 fix: prod pipeline
  .devops/deploy-pipelines.yml
Labels: size/small

#99 feat: [CHK-3967] loading templates in async and cache them
  jest.config.js
  src/__tests__/RetryQueueListener.test.ts
  src/__tests__/templateCache.test.ts
  src/controllers/EmailsControllers.ts
  src/controllers/__tests__/EmailsControllers.test.ts
  src/queues/RetryQueueListener.ts
  src/util/templateCache.ts
Labels: size/large, minor, chart-minor

#101 [CHK-3990] feat: add aws-ses mock
  .env.example
  aws-ses-mock/README.md
  aws-ses-mock/aws-ses-mock.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  jest.setup.js
  src/__tests__/RetryQueueListener.test.ts
  src/__tests__/config.test.ts
  src/app.ts
  src/controllers/HealthControllers.ts
  src/controllers/__tests__/EmailsControllers.test.ts
  src/controllers/__tests__/HealthControllers.test.ts
  src/util/config.ts
Labels: size/small, minor, chart-minor

#102 [CHK-3989] feat: upgrade to node to 22 with mail dependency
  .node-version
  .nvmrc
  Dockerfile
  package.json
  src/controllers/EmailsControllers.ts
  yarn.lock
Labels: size/large, minor, chart-minor

#106 [PIDM-454] fix: expanded prod rollback trigger conditions
  .devops/deploy-pipelines.yml
Labels: size/small, minor, chart-minor

#108 fix: deploy pipeline version bump
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/chart-github-release.yml
  .devops/deploy-pipelines.yml
  .github/workflows/deploy.yml
  .github/workflows/semver_release.yaml
Labels: size/large, chart-patch, patch

#110 fix: version bump command
  .github/workflows/semver_release.yaml
Labels: chart-patch, patch
