Repository pagopa/pagopa-notifications-service, pull requests merged in 2025-02, with the labels that each got.

#86 [CHK-3672] fix: revert upgrade node 20
  .node-version
  .nvmrc
  Dockerfile
  package.json
  yarn.lock
Labels: size/small, minor, chart-minor

#87 [CHK-3762] feat: upgrade to node to 22
  .node-version
  .nvmrc
  Dockerfile
  package.json
  yarn.lock
Labels: size/small, minor, chart-minor

#88 chore: update github release task
  .devops/azure-templates/chart-github-release.yml
Labels: size/small, chart-patch, patch

#89 [CHK-3672] Revert "[CHK-3762] feat: upgrade to node to 22"
  .node-version
  .nvmrc
  Dockerfile
  package.json
  yarn.lock
Labels: size/small, chart-patch, patch

#91 [PIDM-43] fix: set keep alive timeout
  .env.example
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  jest.setup.js
  src/app.ts
  src/controllers/__tests__/HealthControllers.test.ts
  src/util/config.ts
Labels: size/small, chart-patch, patch

#92 [PIDM-205] feat(pdf): remove pdf generation and dependencies
  Dockerfile
  package.json
  src/__tests__/RetryQueueListener.test.ts
  src/app.ts
  src/controllers/EmailsControllers.ts
  src/controllers/__tests__/EmailsControllers.test.ts
  src/queues/RetryQueueListener.ts
  src/templates/poc-1/poc-1.template.pdf.html
  src/templates/poc-2/poc-2.template.pdf.html
  yarn.lock
Labels: size/large, chart-patch, patch

#93 [CHK-3710] Upgrade to node 22
  .node-version
  .nvmrc
  Dockerfile
  package.json
  yarn.lock
Labels: size/large, minor, chart-minor
